package POJO;
// Generated Jun 17, 2019 3:30:39 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartId;
     private CustomerMaster customerMaster;
     private ProductMaster productMaster;
     private int quantity;

    public Cart() {
    }

    public Cart(CustomerMaster customerMaster, ProductMaster productMaster, int quantity) {
       this.customerMaster = customerMaster;
       this.productMaster = productMaster;
       this.quantity = quantity;
    }
   
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
    public CustomerMaster getCustomerMaster() {
        return this.customerMaster;
    }
    
    public void setCustomerMaster(CustomerMaster customerMaster) {
        this.customerMaster = customerMaster;
    }
    public ProductMaster getProductMaster() {
        return this.productMaster;
    }
    
    public void setProductMaster(ProductMaster productMaster) {
        this.productMaster = productMaster;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


