package POJO;
// Generated Jun 17, 2019 3:30:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoryMaster generated by hbm2java
 */
public class CategoryMaster  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private Set subCategoryMasters = new HashSet(0);
     private Set productMasters = new HashSet(0);

    public CategoryMaster() {
    }

	
    public CategoryMaster(String categoryName) {
        this.categoryName = categoryName;
    }
    public CategoryMaster(String categoryName, Set subCategoryMasters, Set productMasters) {
       this.categoryName = categoryName;
       this.subCategoryMasters = subCategoryMasters;
       this.productMasters = productMasters;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getSubCategoryMasters() {
        return this.subCategoryMasters;
    }
    
    public void setSubCategoryMasters(Set subCategoryMasters) {
        this.subCategoryMasters = subCategoryMasters;
    }
    public Set getProductMasters() {
        return this.productMasters;
    }
    
    public void setProductMasters(Set productMasters) {
        this.productMasters = productMasters;
    }




}


