package POJOs;
// Generated 19 Jun, 2019 3:45:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BrandMaster generated by hbm2java
 */
public class BrandMaster  implements java.io.Serializable {


     private Integer brandId;
     private String brandName;
     private Set productMasters = new HashSet(0);

    public BrandMaster() {
    }

	
    public BrandMaster(String brandName) {
        this.brandName = brandName;
    }
    public BrandMaster(String brandName, Set productMasters) {
       this.brandName = brandName;
       this.productMasters = productMasters;
    }
   
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public Set getProductMasters() {
        return this.productMasters;
    }
    
    public void setProductMasters(Set productMasters) {
        this.productMasters = productMasters;
    }




}


