package POJOs;
// Generated 19 Jun, 2019 3:45:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CustomerMaster generated by hbm2java
 */
public class CustomerMaster  implements java.io.Serializable {


     private Integer customerId;
     private String firstName;
     private String lastName;
     private String contactNo;
     private String email;
     private String password;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private int pincode;
     private Set orderMasters = new HashSet(0);
     private Set carts = new HashSet(0);

    public CustomerMaster() {
    }

	
    public CustomerMaster(String firstName, String lastName, String contactNo, String email, String password, String addressLine1, int pincode) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.contactNo = contactNo;
        this.email = email;
        this.password = password;
        this.addressLine1 = addressLine1;
        this.pincode = pincode;
    }
    public CustomerMaster(String firstName, String lastName, String contactNo, String email, String password, String addressLine1, String addressLine2, String addressLine3, int pincode, Set orderMasters, Set carts) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.contactNo = contactNo;
       this.email = email;
       this.password = password;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.pincode = pincode;
       this.orderMasters = orderMasters;
       this.carts = carts;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


