package POJOs;
// Generated 19 Jun, 2019 3:45:22 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private Integer orderDetaiId;
     private OrderMaster orderMaster;
     private ProductMaster productMaster;
     private int quantity;
     private double price;

    public OrderDetail() {
    }

    public OrderDetail(OrderMaster orderMaster, ProductMaster productMaster, int quantity, double price) {
       this.orderMaster = orderMaster;
       this.productMaster = productMaster;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getOrderDetaiId() {
        return this.orderDetaiId;
    }
    
    public void setOrderDetaiId(Integer orderDetaiId) {
        this.orderDetaiId = orderDetaiId;
    }
    public OrderMaster getOrderMaster() {
        return this.orderMaster;
    }
    
    public void setOrderMaster(OrderMaster orderMaster) {
        this.orderMaster = orderMaster;
    }
    public ProductMaster getProductMaster() {
        return this.productMaster;
    }
    
    public void setProductMaster(ProductMaster productMaster) {
        this.productMaster = productMaster;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


