package POJOs;
// Generated 19 Jun, 2019 3:45:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCategoryMaster generated by hbm2java
 */
public class SubCategoryMaster  implements java.io.Serializable {


     private Integer subCategoryId;
     private CategoryMaster categoryMaster;
     private String subCategoryName;
     private Set productMasters = new HashSet(0);

    public SubCategoryMaster() {
    }

	
    public SubCategoryMaster(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
    public SubCategoryMaster(CategoryMaster categoryMaster, String subCategoryName, Set productMasters) {
       this.categoryMaster = categoryMaster;
       this.subCategoryName = subCategoryName;
       this.productMasters = productMasters;
    }
   
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }
    public CategoryMaster getCategoryMaster() {
        return this.categoryMaster;
    }
    
    public void setCategoryMaster(CategoryMaster categoryMaster) {
        this.categoryMaster = categoryMaster;
    }
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
    public Set getProductMasters() {
        return this.productMasters;
    }
    
    public void setProductMasters(Set productMasters) {
        this.productMasters = productMasters;
    }




}


