package POJO;
// Generated Jun 17, 2019 3:30:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductMaster generated by hbm2java
 */
public class ProductMaster  implements java.io.Serializable {


     private Integer productId;
     private BrandMaster brandMaster;
     private CategoryMaster categoryMaster;
     private SubCategoryMaster subCategoryMaster;
     private String productName;
     private String imageName;
     private String description;
     private double price;
     private int inStock;
     private double categoryDiscount;
     private double brandDiscount;
     private byte[] productImagel;
     private Set orderDetails = new HashSet(0);
     private Set carts = new HashSet(0);

    public ProductMaster() {
    }

	
    public ProductMaster(BrandMaster brandMaster, CategoryMaster categoryMaster, SubCategoryMaster subCategoryMaster, String productName, String description, double price, int inStock, double categoryDiscount, double brandDiscount, byte[] productImagel) {
        this.brandMaster = brandMaster;
        this.categoryMaster = categoryMaster;
        this.subCategoryMaster = subCategoryMaster;
        this.productName = productName;
        this.description = description;
        this.price = price;
        this.inStock = inStock;
        this.categoryDiscount = categoryDiscount;
        this.brandDiscount = brandDiscount;
        this.productImagel = productImagel;
    }
    public ProductMaster(BrandMaster brandMaster, CategoryMaster categoryMaster, SubCategoryMaster subCategoryMaster, String productName, String imageName, String description, double price, int inStock, double categoryDiscount, double brandDiscount, byte[] productImagel, Set orderDetails, Set carts) {
       this.brandMaster = brandMaster;
       this.categoryMaster = categoryMaster;
       this.subCategoryMaster = subCategoryMaster;
       this.productName = productName;
       this.imageName = imageName;
       this.description = description;
       this.price = price;
       this.inStock = inStock;
       this.categoryDiscount = categoryDiscount;
       this.brandDiscount = brandDiscount;
       this.productImagel = productImagel;
       this.orderDetails = orderDetails;
       this.carts = carts;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public BrandMaster getBrandMaster() {
        return this.brandMaster;
    }
    
    public void setBrandMaster(BrandMaster brandMaster) {
        this.brandMaster = brandMaster;
    }
    public CategoryMaster getCategoryMaster() {
        return this.categoryMaster;
    }
    
    public void setCategoryMaster(CategoryMaster categoryMaster) {
        this.categoryMaster = categoryMaster;
    }
    public SubCategoryMaster getSubCategoryMaster() {
        return this.subCategoryMaster;
    }
    
    public void setSubCategoryMaster(SubCategoryMaster subCategoryMaster) {
        this.subCategoryMaster = subCategoryMaster;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getInStock() {
        return this.inStock;
    }
    
    public void setInStock(int inStock) {
        this.inStock = inStock;
    }
    public double getCategoryDiscount() {
        return this.categoryDiscount;
    }
    
    public void setCategoryDiscount(double categoryDiscount) {
        this.categoryDiscount = categoryDiscount;
    }
    public double getBrandDiscount() {
        return this.brandDiscount;
    }
    
    public void setBrandDiscount(double brandDiscount) {
        this.brandDiscount = brandDiscount;
    }
    public byte[] getProductImagel() {
        return this.productImagel;
    }
    
    public void setProductImagel(byte[] productImagel) {
        this.productImagel = productImagel;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


